### ISSUE TITLE
Bug: Lualine setup kills nvim intro.

### ISSUE THREAD

**Issue by hiddenruins** [hoob3rt/lualine.nvim#259]
### Self Checks

- [ X] I'm using the latest lualine and neovim nightly.
- [ X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Put `lualine.setup {}` in the config
Start `nvim`

### Actual behaviour
Lualine kills the intro screen
![image](https://user-images.githubusercontent.com/5569621/119356998-c8013180-bcc6-11eb-915d-2c0700ace588.png)

### Expected behaviour
Starting up nvim should display the intro

![image](https://user-images.githubusercontent.com/5569621/119356956-ba4bac00-bcc6-11eb-8b68-a0b712277de0.png)

### Minimal config to reproduce the issue
```lua
require('lualine').setup{}
```

<details>
<summary>Config</summary>

lualine.setup{
  options = {
    theme = 'gruvbox_material',
  },
};
</details>

**Comment by hoob3rt** [comment]
I'm aware of this and looked into it for some time now. Seems like all lua based plugins cause this? I'm not sure tbh but that's all I found while trying to debug it

**Comment by hiddenruins** [comment]
> I'm aware of this and looked into it for some time now. Seems like all lua based plugins cause this? I'm not sure tbh but that's all I found while trying to debug it

Other lua don't cause this as per my experience.
Lualine by default doesn't kill the intro but as soon as just `require('lualine').setup{}` added to the config, it kills the intro.

**Comment by kaspergrubbe** [comment]
I just noticed this as well, I have other Lua packages installed that doesn't cause it.

**Comment by zapling** [comment]
Same here, not that big of deal, but disabling `require('lualine').setup{}` fixes it.

**Comment by zapling** [comment]
Seems to be related to the `vim.cmd` call used here. If I comment that one out the intro is not cleared. https://github.com/hoob3rt/lualine.nvim/blob/9726824f1dcc8907632bc7c32f9882f26340f815/lua/lualine/highlight.lua#L29

**Comment by shadmansaleh** [comment]
No this is realated to async loading lualine

**Comment by yufengwng** [comment]
Switched to Lualine recently (thanks!), and noticed the same issue. After some digging, I found it was related to async loading (as @shadmansaleh suggested). I think this is because Lualine does the theme asynchronously and the redraw will remove the intro msg (some info in `:h :intro`).

I worked around this by adding an option to apply theme synchronously in [my fork](https://github.com/yufengwng/lualine.nvim/commit/d631667c39b9c7e0bd85f0ecdb955d6f1c34e031). Not sure if it's right, but it seems to work for me.

**Comment by zapling** [comment]
> Switched to Lualine recently (thanks!), and noticed the same issue. After some digging, I found it was related to async loading (as @shadmansaleh suggested). I think this is because Lualine does the theme asynchronously and the redraw will remove the intro msg (some info in `:h :intro`).
> 
> I worked around this by adding an option to apply theme synchronously in [my fork](https://github.com/yufengwng/lualine.nvim/commit/d631667c39b9c7e0bd85f0ecdb955d6f1c34e031). Not sure if it's right, but it seems to work for me.

That workaround didn't quite fully solve it for me. The intro was displayed but my status bar didn't have the correct colors. I had a go at my own workaround and this seems to have solved my case at least (although I have only tested it for a few minutes).
```
diff --git a/lua/lualine/init.lua b/lua/lualine/init.lua
index 10c252d..7c0dd57 100644
--- a/lua/lualine/init.lua
+++ b/lua/lualine/init.lua
@@ -151,6 +151,10 @@ local function setup_theme()
             autocmd ColorScheme * lua require'lualine.utils.utils'.reload_highlights()
           augroup END
           ]], false)
+        local num_args = vim.api.nvim_eval(vim.api.nvim_exec('echo argc()', true))
+        if num_args == 0 then
+            vim.api.nvim_exec('intro', false)
+        end
         async_loader:close()
       end))
   async_loader:send()

```

**Comment by ibhagwan** [comment]
Just [solved this for feline.nvim](https://github.com/famiu/feline.nvim/pull/24) - you might find the information inside helpful.

**Comment by shadmansaleh** [comment]
Fixed in #311

**Comment by shibotto** [comment]
As of 2d6108e07f5888a42dee37598570bac990ca1297 this seems to be an issue again.

(Very) minimal config:

```vim
call plug#begin("/tmp/intro/.local/share/nvim/plugged")
Plug 'nvim-lualine/lualine.nvim'
call plug#end()

lua << END
require'lualine'.setup {

}
END
```

Checking out to 5f68f070e4f7158517afc55f125a6f5ed1f7db47 solves the problem.

**Comment by shadmansaleh** [comment]
I have even more minimal config without lualine. Simply setting statusline from a scheduled function causes it while setting outside of scheduled function doesn't.

```lua
-- file: minimal_init.lua
vim.o.stl = 'asdf'
vim.schedule(function () vim.o.stl = 'jkl;' end)
```
```sh
nvim --clean -u minimal_init.lua
```

With current redraw mechanics we can't quite avoid setting statusline from scheduled context . I guess we could try report it to nvim devs and see what they think about it if it's a bug or intended behavior.

**Comment by sbmueller** [comment]
I also experience this issue on edca2b0 . Could we reopen it to indicate it is not resolved?

**Comment by eeeXun** [comment]
I encounter this problem with with winbar is setup.

**Comment by jsatk** [comment]
Still an issue for me as well.

**Comment by erikeah** [comment]
I'm also experimenting this issue.

**Comment by eoh-bse** [comment]
There are a lot of other plugins like `nvim-tree` and `bufferline` that kill the intro. I got sick of the issue and I just wrote a very simple plugin (~100 lines) that works around this issue and displays a simple neovim logo.
If you are interested: https://github.com/eoh-bse/minintro.nvim

**Comment by CFiggers** [comment]
Also experiencing this issue.

**Comment by Triavanicus** [comment]
I am having this issue only when I set `section_separators` to something other than `''`

**Comment by Tussis88** [comment]
> I am having this issue only when I set `section_separators` to something other than `''` Modifying `component_separators` works fine.

I've  tried this and it worked. Setting the `section_separators` to blank  *fix* the issue. Guess we now know what is the cause

**Comment by Jervx** [comment]
I added `cmdheight=2` then execute `intro` command, and then `cmdheight=1`, I have read that the separator for lualine causes a redraw, so I think calling the intro after the setup would work but I'm not sure to be honest but it works for me.

![image](https://github.com/nvim-lualine/lualine.nvim/assets/48374007/097e1e64-2d3b-4f8f-8b3e-52c7e8a5e370)

It works but I have the anoying `Press ENTER or type command to continue`. Please let me know how to disable this when using vim.cmd using lua

![image](https://github.com/nvim-lualine/lualine.nvim/assets/48374007/35ddd0cd-2d74-450a-a266-fe620a75a8cc)

**Comment by Jervx** [comment]
I forget about this, and it seems like it was fixed now May 27, 2024

![image](https://github.com/nvim-lualine/lualine.nvim/assets/48374007/629ed7c1-8322-49de-a091-250f753723ba)

**Comment by wasowski** [comment]
I can confirm that non-empty `section_separators` work with lualine and neovim 0.10.1, and the intro does not disappear.
